name: Trigger Steam Workshop deploy
on:
  push:
    branches:
      - master
jobs:
  jenkins:
    name: Trigger Jenkins job
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/jenkins-action@master
        with:
          url: "https://jenkins.rmg.david-sima.dev/"
          user: "the24thds"
          token: ${{ secrets.TOKEN }}
          job: "new_enclaves_steam_deploy"
