name: Create new release
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Create release draft
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        lfs: true
    - name: Checkout LFS objects
      run: git lfs checkout
    - name: Fix locs
      run: |
        chmod +x ./fix_crowdin_localisation_files.sh
        ./fix_crowdin_localisation_files.sh new_enclaves
    - name: Archive New Enclaves
      uses: thedoctor0/zip-release@master
      with:
        filename: 'new_enclaves_vx.x.x.zip'
        exclusions: '*.git* /*assets/* /*compatibility-patches/* /*addons/* /*steam/* /*vanilla_cache/* .all-contributorsrc README.md crowdin.yml'
    - name: Archive New Enclaves Compatibility Patches
      uses: thedoctor0/zip-release@master
      with:
        filename: 'new_enclaves_compatibility_patches.zip'
        path: 'compatibility-patches/'
    - name: Create release with artifacts
      uses: ncipollo/release-action@v1
      with:
        artifacts: 'new_enclaves_vx.x.x.zip,new_enclaves_compatibility_patches.zip'
        name: 'New Enclaves vx.x.x'
        body: 'Available on: - Steam Workshop: https://steamcommunity.com/sharedfiles/filedetails/?id=2356224372'
        tag: 'vx.x.x'
        commit: 'master'
        draft: true
        token: ${{ secrets.GITHUB_TOKEN }}
  # jenkins:
  #   name: Trigger Jenkins job
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: appleboy/jenkins-action@master
  #       with:
  #         url: "https://jenkins.rmg.david-sima.dev/"
  #         user: "the24thds"
  #         token: ${{ secrets.TOKEN }}
  #         job: "new_enclaves_steam_deploy"
    
